language: python
python:
    - "2.7"
sudo: false
dist: trusty
install: "pip install pip --upgrade"
script: make plot
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
